* tumblr-identity-manager

This is a demonstration project that isolates a few concepts related to
seamlessly combining a Clojure back-end with a rich JavaScript front-end, in
the case where common structures are shared between layers.

Concepts covered:
- Automated case style conversion.
- Traversing forms with clojure.walk.
- Memoization and threshold profiling with clojure.core.memoize.

These concepts will be presented at the National Capital Area Clojure Users
Group on 2015-07-08.  See the [[http://www.meetup.com/Cap-Clug/events/223192323/][event page]] for details.

* Usage

To just start the application without a REPL:

#+BEGIN_SRC sh
lein ring server
#+END_SRC

To run the application and connect to the REPL:

#+BEGIN_SRC sh
lein repl :headless
#+END_SRC

Connect to the REPL in Emacs, then run:

#+BEGIN_SRC clojure
(boot)
#+END_SRC

to start the server.  You can then navigate to =http://localhost:3000= to
interact with the front end.

* License

Copyright © 2015

Distributed under the GNU Public License version 3.0.
